import { generateReport, type ReportType } from './report'

interface ToolResult {
  name: string
  data: unknown
}

function detectReportType(toolName: string): ReportType | null {
  if (toolName === 'protein_benchmark') return 'benchmark'
  if (toolName === 'mutation_priority_score') return 'mutation_score'
  if (toolName === 'gromacs_md') return 'md'
  if (toolName === 'blast_search') return 'blast'
  return null
}

const TOOL_NAMES: Record<string, string> = {
  protein_benchmark: 'Protein Benchmark',
  mutation_priority_score: 'Mutation Priority Score',
  gromacs_md: 'MD Simulation',
  blast_search: 'BLAST Search',
}

export function collectResults(content: string, toolCalls?: Array<{ name: string; resultPreview?: string }>): ToolResult[] {
  const results: ToolResult[] = []
  if (!toolCalls) return results

  for (const tc of toolCalls) {
    const type = detectReportType(tc.name)
    if (!type || !tc.resultPreview) continue
    try {
      const data = JSON.parse(tc.resultPreview.replace(/'/g, '"'))
      results.push({ name: tc.name, data })
    } catch {
      // Skip unparseable results
    }
  }
  return results
}

export function generateConversationReport(
  title: string,
  results: ToolResult[],
  synthesis?: string
): string {
  const sections: string[] = []

  sections.push(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${title}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 13px; line-height: 1.6; color: #1a1a1a; max-width: 960px; margin: 0 auto; padding: 40px 24px; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  h2 { font-size: 18px; margin: 32px 0 12px; padding-bottom: 6px; border-bottom: 2px solid #2563eb; color: #1e40af; }
  .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; color: #6b7280; padding: 8px 12px; background: #f0f9ff; border-bottom: 2px solid #bfdbfe; }
  td { padding: 8px 12px; border-bottom: 1px solid #f0f9ff; font-size: 12px; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; }
  .badge-green { background: #d1fae5; color: #065f46; }
  .code { font-family: 'SF Mono', monospace; background: #f3f4f6; padding: 1px 6px; border-radius: 4px; font-size: 12px; }
  .metric-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; margin: 12px 0; }
  .metric-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px; }
  .metric-label { font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
  .metric-value { font-size: 20px; font-weight: 700; font-family: 'SF Mono', monospace; margin-top: 4px; }
  .toc { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 16px 0; }
  .toc a { color: #2563eb; text-decoration: none; }
  .synthesis { background: #f0f9ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 20px; margin: 16px 0; line-height: 1.8; }
  footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
  @media print { body { padding: 20px; } h2 { break-before: page; } }
</style></head><body>`)

  // Title
  sections.push(`<h1>${title}</h1>`)
  sections.push(`<p class="subtitle">Protein AI Platform — ${new Date().toISOString().slice(0, 10)} — ${results.length} analyses</p>`)

  // TOC
  if (results.length > 1) {
    sections.push('<div class="toc"><strong>Contents</strong><ol style="margin-top:8px;padding-left:20px">')
    results.forEach((r, i) => {
      const label = TOOL_NAMES[r.name] || r.name
      sections.push(`<li><a href="#section-${i}">${label}</a></li>`)
    })
    if (synthesis) sections.push('<li><a href="#synthesis">Synthesis & Recommendations</a></li>')
    sections.push('</ol></div>')
  }

  // Individual reports
  results.forEach((r, i) => {
    const type = detectReportType(r.name)
    const label = TOOL_NAMES[r.name] || r.name
    if (type) {
      sections.push(`<h2 id="section-${i}">${i + 1}. ${label}</h2>`)
      // Strip outer HTML wrapper and get just the body
      const full = generateReport(type, r.data)
      const bodyMatch = full.match(/<body>([\s\S]*)<\/body>/)
      if (bodyMatch) {
        sections.push(bodyMatch[1])
      }
    }
  })

  // Synthesis
  if (synthesis) {
    sections.push('<h2 id="synthesis">Synthesis & Recommendations</h2>')
    sections.push(`<div class="synthesis">${synthesis.replace(/\n/g, '<br>')}</div>`)
  }

  sections.push(`<footer>Generated by Protein AI Platform &mdash; ${new Date().toLocaleString()}</footer>`)
  sections.push('</body></html>')

  return sections.join('\n')
}

export function downloadConversationReport(title: string, results: ToolResult[], synthesis?: string) {
  const html = generateConversationReport(title, results, synthesis)
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `protein-report-${Date.now()}.html`
  a.click()
  URL.revokeObjectURL(url)
}
